#!/bin/bash

echo OS PALPITES DO JOGO DE HOJE DO JOGO DO BICHO DAS 11:30H É: 
sleep 2
shuf -i 0001-9999 -n 5; shuf -i 001-999 -n 1
echo Resultado gerado em 
date
echo PARABÉNS ! ! !
sleep 1
echo DIZ PRA GENTE SE VC GANHOU COM NOSSOS PALPITES! 
sleep 15 
clear

